version: '3.8'

services:
  app:
    build: .
    container_name: itsplanned-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env.production
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: itsplanned-db
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 